openapi: 3.0.0
info:
  title: API per la gestione di allevamenti animali
  description: API per la gestione di animali in un allevamento, con informazioni su nome, tipo, quantità, prezzo, superficie, e giorni di crescita.
  version: 1.0.0

paths:
  /animali:
    get:
      summary: Recupera la lista di tutti gli animali dell'allevamento
      responses:
        '200':
          description: Una lista di animali
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Animale'

    post:
      summary: Crea un nuovo animale nell'allevamento
      requestBody:
        description: Dati del nuovo animale
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Animale'
      responses:
        '201':
          description: Animale creato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Animale'

  /animali/{id}:
    get:
      summary: Recupera i dettagli di un animale specifico
      parameters:
        - in: path
          name: id
          required: true
          description: ID dell'animale
          schema:
            type: integer
      responses:
        '200':
          description: Dettagli dell'animale
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Animale'
        '404':
          description: Animale non trovato

    put:
      summary: Aggiorna i dettagli di un animale
      parameters:
        - in: path
          name: id
          required: true
          description: ID dell'animale
          schema:
            type: integer
      requestBody:
        description: Nuovi dati dell'animale
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Animale'
      responses:
        '200':
          description: Animale aggiornato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Animale'
        '404':
          description: Animale non trovato

    delete:
      summary: Elimina un animale
      parameters:
        - in: path
          name: id
          required: true
          description: ID dell'animale
          schema:
            type: integer
      responses:
        '204':
          description: Animale eliminato con successo
        '404':
          description: Animale non trovato

components:
  schemas:
    Animale:
      type: object
      required:
        - tipo
        - numero
        - prezzo
      properties:
        id:
          type: integer
          description: ID dell'animale
        nome:
          type: string
          description: Il nome dell'animale
        tipo:
          type: string
          description: Il tipo di animale (ad esempio, "mucca", "pecora", "pollo")
        prezzo:
          type: integer
          description: Il prezzo per unità dell'animale


