openapi: 3.0.0
info:
  title: API per la gestione di allevamenti animali acquatici
  description: API per la gestione di animali acquatici in un allevamento, con informazioni su nome, tipo, quantità, prezzo, superficie acquatica e ambiente.
  version: 1.0.0

paths:
  /pesci:
    get:
      summary: Recupera la lista di tutti gli animali acquatici dell'allevamento
      responses:
        '200':
          description: Una lista di animali acquatici
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pesca'

    post:
      summary: Crea un nuovo animale acquatico nell'allevamento
      requestBody:
        description: Dati del nuovo animale acquatico
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pesca'
      responses:
        '201':
          description: Animale acquatico creato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pesca'

  /pesci/{id}:
    get:
      summary: Recupera i dettagli di un animale acquatico specifico
      parameters:
        - in: path
          name: id
          required: true
          description: ID dell'animale acquatico
          schema:
            type: integer
      responses:
        '200':
          description: Dettagli dell'animale acquatico
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pesca'
        '404':
          description: Animale non trovato

    put:
      summary: Aggiorna i dettagli di un animale acquatico
      parameters:
        - in: path
          name: id
          required: true
          description: ID dell'animale acquatico
          schema:
            type: integer
      requestBody:
        description: Nuovi dati dell'animale acquatico
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pesca'
      responses:
        '200':
          description: Animale acquatico aggiornato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pesca'
        '404':
          description: Animale non trovato

    delete:
      summary: Elimina un animale acquatico
      parameters:
        - in: path
          name: id
          required: true
          description: ID dell'animale acquatico
          schema:
            type: integer
      responses:
        '204':
          description: Animale acquatico eliminato con successo
        '404':
          description: Animale non trovato

components:
  schemas:
    Pesca:
      type: object
      required:
        - tipo
        - prezzo
        - stockPesce
        - profondita
      properties:
        id:
          type: integer
          description: ID dell'animale acquatico
        nome:
          type: string
          description: Il nome dell'animale acquatico (ad esempio, "trota", "spigola", "ostrica")
        tipo:
          type: string
          description: Il tipo di animale acquatico (ad esempio, "pesce", "mollusco", "crostaaceo")
        stockPesce:
          type: integer
          description: biomassa pesce che si trobna nella zona
        profondita:
          type: int
          description: profondita della pesca
        prezzo:
          type: integer
          description: Il prezzo per unità dell'animale acquatico
