openapi: 3.0.0
info:
  title: API per la gestione di allevamenti animali acquatici
  description: API per la gestione di animali acquatici in un allevamento, con informazioni su nome, tipo, quantità, prezzo, superficie acquatica e ambiente.
  version: 1.0.0

paths:
  /pesci:
    get:
      summary: Recupera la lista di tutti gli animali acquatici dell'allevamento
      responses:
        '200':
          description: Una lista di animali acquatici
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Animale'

    post:
      summary: Crea un nuovo animale acquatico nell'allevamento
      requestBody:
        description: Dati del nuovo animale acquatico
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Animale'
      responses:
        '201':
          description: Animale acquatico creato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Animale'

  /pesci/{id}:
    get:
      summary: Recupera i dettagli di un animale acquatico specifico
      parameters:
        - in: path
          name: id
          required: true
          description: ID dell'animale acquatico
          schema:
            type: integer
      responses:
        '200':
          description: Dettagli dell'animale acquatico
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Animale'
        '404':
          description: Animale non trovato

    put:
      summary: Aggiorna i dettagli di un animale acquatico
      parameters:
        - in: path
          name: id
          required: true
          description: ID dell'animale acquatico
          schema:
            type: integer
      requestBody:
        description: Nuovi dati dell'animale acquatico
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Animale'
      responses:
        '200':
          description: Animale acquatico aggiornato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Animale'
        '404':
          description: Animale non trovato

    delete:
      summary: Elimina un animale acquatico
      parameters:
        - in: path
          name: id
          required: true
          description: ID dell'animale acquatico
          schema:
            type: integer
      responses:
        '204':
          description: Animale acquatico eliminato con successo
        '404':
          description: Animale non trovato

components:
  schemas:
    Animale:
      type: object
      required:
        - tipo
        - stock
        - prezzo
        - superficie
        - ambiente
      properties:
        id:
          type: integer
          description: ID dell'animale acquatico
        nome:
          type: string
          description: Il nome dell'animale acquatico (ad esempio, "trota", "spigola", "ostrica")
        tipo:
          type: string
          description: Il tipo di animale acquatico (ad esempio, "pesce", "mollusco", "crostaaceo")
        quantita:
          type: integer
          description: La quantità di animali acquatici disponibili
        prezzo:
          type: integer
          description: Il prezzo per unità dell'animale acquatico
        superficie:
          type: integer
          description: La superficie acquatica in ettari o metri quadrati dedicata all'allevamento (ad esempio, vasche, stagni, acquari)
        ambiente:
          type: string
          description: Il tipo di ambiente acquatico (ad esempio, "acquario", "laguna", "vasca", "acqua salata", "acqua dolce")

