openapi: 3.0.0
info:
  title: API per la gestione di prodotti di sivicoltura
  description: API per la gestione di prodotti di sivicoltura, con informazioni su nome, tipo, quantità, prezzo, superficie e giorni di crescita.
  version: 1.0.0

paths:
  /sivicoltura:
    get:
      summary: Recupera la lista di tutti i prodotti di sivicoltura
      responses:
        '200':
          description: Una lista di prodotti di sivicoltura
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Sivicoltura'

    post:
      summary: Crea un nuovo prodotto di sivicoltura
      requestBody:
        description: Dati del nuovo prodotto di sivicoltura
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sivicoltura'
      responses:
        '201':
          description: Prodotto di sivicoltura creato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sivicoltura'

  /sivicoltura/{id}:
    get:
      summary: Recupera i dettagli di un prodotto di sivicoltura specifico
      parameters:
        - in: path
          name: id
          required: true
          description: ID del prodotto di sivicoltura
          schema:
            type: integer
      responses:
        '200':
          description: Dettagli del prodotto di sivicoltura
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sivicoltura'
        '404':
          description: Prodotto non trovato

    put:
      summary: Aggiorna i dettagli di un prodotto di sivicoltura
      parameters:
        - in: path
          name: id
          required: true
          description: ID del prodotto di sivicoltura
          schema:
            type: integer
      requestBody:
        description: Nuovi dati del prodotto di sivicoltura
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sivicoltura'
      responses:
        '200':
          description: Prodotto di sivicoltura aggiornato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sivicoltura'
        '404':
          description: Prodotto non trovato

    delete:
      summary: Elimina un prodotto di sivicoltura
      parameters:
        - in: path
          name: id
          required: true
          description: ID del prodotto di sivicoltura
          schema:
            type: integer
      responses:
        '204':
          description: Prodotto di sivicoltura eliminato con successo
        '404':
          description: Prodotto non trovato

components:
  schemas:
    Sivicoltura:
      type: object
      required:
        - nome
        - tipo
        - prezzo
        - superficie
        - giorniCrescita
      properties:
        id:
          type: integer
          description: ID del prodotto di sivicoltura
        nome:
          type: string
          description: Il nome del prodotto di sivicoltura (ad esempio, "albero di quercia", "abete rosso")
        tipo:
          type: string
          description: Il tipo di prodotto di sivicoltura (ad esempio, "albero", "pianta", "legno")

        prezzo:
          type: integer
          description: Il prezzo per unità del prodotto di sivicoltura
        superficie:
          type: integer
          description: La superficie in ettari per unità del prodotto di sivicoltura
        giorniCrescita:
          type: integer
          description: Il numero di giorni di crescita standard per il prodotto di sivicoltura
